INSERT INTO word(id, definition, word) VALUES
                                           (1, 'Etwas, das man auf den Kopf setzt, um sich vor der Sonne zu schützen', 'Hut'),
                                           (2, 'Ein Tier, das schnurrt und Mäuse fängt', 'Katze'),
                                           (3, 'Damit fährt man zur Schule oder zur Arbeit, hat vier Räder', 'Auto'),
                                           (4, 'Fliegendes Fahrzeug mit Flügeln', 'Flugzeug'),
                                           (5, 'Ein langes, dünnes Ding, aus dem Wasser kommt, wenn man es dreht', 'Wasserhahn'),
                                           (6, 'Ein Tier, das laut bellt und gerne Stöckchen holt', 'Hund'),
                                           (7, 'Süßes Essen aus Kakao, das schmilzt, wenn es warm ist', 'Schokolade'),
                                           (8, 'Damit kann man telefonieren, schreiben und Fotos machen', 'Handy'),
                                           (9, 'Flüssigkeit, die man trinkt, um den Durst zu löschen', 'Wasser'),
                                           (10, 'Ein runder Ball aus Teig mit Belag, meist aus Italien', 'Pizza'),
                                           (11, 'Ein Tier, das im Dschungel lebt und gerne Bananen isst', 'Affe'),
                                           (12, 'Kleines geflügeltes Insekt, das im Sommer sticht', 'Mücke'),
                                           (13, 'Leuchtet am Himmel in der Nacht', 'Mond'),
                                           (14, 'Ein Gefäß aus Glas oder Plastik, um Getränke aufzubewahren', 'Flasche'),
                                           (15, 'Ein Tier mit langem Hals aus Afrika', 'Giraffe'),
                                           (16, 'Ein großes Gebäude, in dem man wohnt', 'Haus'),
                                           (17, 'Man benutzt es, um Haare zu trocknen', 'Fön'),
                                           (18, 'Ein runder Gegenstand, mit dem man Fußball spielt', 'Ball'),
                                           (19, 'Ein Mensch, der Essen in einem Restaurant zubereitet', 'Koch'),
                                           (20, 'Gefährt mit zwei Rädern, das man mit den Füßen bewegt', 'Fahrrad'),
                                           (21, 'Zeigt dir, wie spät es ist', 'Uhr'),
                                           (22, 'Ein Tier mit Rüssel', 'Elefant'),
                                           (23, 'Trägt man, wenn es regnet', 'Regenjacke'),
                                           (24, 'Ein kleines, rundes Gerät, das leuchtet, wenn man drückt', 'Taschenlampe'),
                                           (25, 'Sitzt auf einem Baum, macht "Kuckuck"', 'Vogel'),
                                           (26, 'Ein Ort mit Sand und Meer', 'Strand'),
                                           (27, 'Manche haben Höhenangst davor', 'Leiter'),
                                           (28, 'Ein weißes Pulver, aus dem Brot gemacht wird', 'Mehl'),
                                           (29, 'Großes Tier mit Mähne, König der Tiere', 'Löwe'),
                                           (30, 'Ein Ort, wo man Bücher ausleiht', 'Bibliothek'),
                                           (31, 'Fliegendes Fahrzeug mit Rotoren', 'Hubschrauber'),
                                           (32, 'Sorgt für Sicherheit auf der Straße', 'Polizist'),
                                           (33, 'Rundes Gemüse, oft in Salaten, rot und saftig', 'Tomate'),
                                           (34, 'Kleines Tier mit Schale, das langsam kriecht', 'Schnecke'),
                                           (35, 'Ein Baum verliert sie im Herbst', 'Blatt'),
                                           (36, 'Fahrzeug mit viel Platz, oft für Lieferungen', 'LKW'),
                                           (37, 'Man isst es zum Frühstück, aus Eiern', 'Rührei'),
                                           (38, 'Hilft dir, Sachen zu tragen, wird auf dem Rücken getragen', 'Rucksack'),
                                           (39, 'Steht in der Küche, kühlt Lebensmittel', 'Kühlschrank'),
                                           (40, 'Ein Ort zum Schwimmen', 'Schwimmbad'),
                                           (41, 'Dreieckiges Musikinstrument aus Metall', 'Triangel'),
                                           (42, 'Langes, dünnes Nudelgericht aus Italien', 'Spaghetti'),
                                           (43, 'Etwas, das man auf dem Kopf trägt und es warm hält', 'Mütze'),
                                           (44, 'Ein schwarzes Tier, das fliegen kann und nachts aktiv ist', 'Fledermaus'),
                                           (45, 'Mit diesem Werkzeug schlägt man Nägel ein', 'Hammer'),
                                           (46, 'Man sitzt darauf, wenn man isst', 'Stuhl'),
                                           (47, 'Damit schreibt man auf Papier, aber nicht mit Tinte', 'Bleistift'),
                                           (48, 'Kleidung für untenrum', 'Hose'),
                                           (49, 'Ein Tier mit Hörnern, das Milch gibt', 'Kuh'),
                                           (50, 'Ort, an dem man Filme sieht', 'Kino'),
                                           (51, 'Schnelles Verkehrsmittel auf Schienen', 'Zug'),
                                           (52, 'Man trägt sie an den Füßen', 'Schuhe'),
                                           (53, 'Ein Insekt mit Flügeln und vielen Farben', 'Schmetterling'),
                                           (54, 'Großer Berg, aus dem Lava kommen kann', 'Vulkan'),
                                           (55, 'Man benutzt es zum Graben', 'Schaufel'),
                                           (56, 'Ein Tier mit vielen Beinen, spinnt Netze', 'Spinne'),
                                           (57, 'Man trägt es am Finger', 'Ring'),
                                           (58, 'Ein Spielzeug, das man wirft und wieder fängt', 'Frisbee'),
                                           (59, 'Trägt man bei Sonne auf der Nase', 'Sonnenbrille'),
                                           (60, 'Schnelles Fahrzeug mit zwei Rädern und Motor', 'Motorrad'),
                                           (61, 'Ein Raubtier mit Streifen', 'Tiger'),
                                           (62, 'Flaches Ding mit Knöpfen, daran tippt man beim Schreiben', 'Tastatur'),
                                           (63, 'Kleines Gerät, das man zum Fernsehen nutzt', 'Fernbedienung'),
                                           (64, 'Etwas, das man mit Wasser benutzt, um sauber zu werden', 'Seife'),
                                           (65, 'Dient zum Verschließen von Türen', 'Schlüssel'),
                                           (66, 'Ort, wo kranke Menschen behandelt werden', 'Krankenhaus'),
                                           (67, 'Ein Tier, das watschelt und gerne schwimmt', 'Ente'),
                                           (68, 'Leuchtendes Teil im Himmel, das Wärme gibt', 'Sonne'),
                                           (69, 'Ein großer Laster, der Müll abholt', 'Müllwagen'),
                                           (70, 'Etwas, das sich dreht und Musik spielt', 'Schallplatte'),
                                           (71, 'Maschine zum Wäschewaschen', 'Waschmaschine'),
                                           (72, 'Ein scharfes Werkzeug zum Schneiden', 'Messer'),
                                           (73, 'Lebensmittel mit Löchern, aus Milch gemacht', 'Käse'),
                                           (74, 'Etwas, das man liest und viele Seiten hat', 'Buch'),
                                           (75, 'Kleiner, süßer Snack mit Zucker oder Schokolade', 'Keks'),
                                           (76, 'Ein kleiner, grüner Hüpfer', 'Frosch'),
                                           (77, 'Etwas, das die Luft bewegt und kühlt', 'Ventilator'),
                                           (78, 'Gerät zum Fotografieren', 'Kamera'),
                                           (79, 'Kleines Auto, das Kinder fahren', 'Spielzeugauto'),
                                           (80, 'Man pustet rein, dann macht es Musik', 'Flöte'),
                                           (81, 'Ein magisches Wesen mit Horn', 'Einhorn'),
                                           (82, 'Großer Fisch mit Zähnen', 'Hai'),
                                           (83, 'Schnelle Straße für Autos', 'Autobahn'),
                                           (84, 'Gerät zum Toasten von Brot', 'Toaster'),
                                           (85, 'Ein bunter Lichtstreifen nach dem Regen', 'Regenbogen'),
                                           (86, 'Man wirft es in den Briefkasten', 'Brief'),
                                           (87, 'Kleines Fahrzeug, das man schiebt und Kinder sitzen drin', 'Kinderwagen'),
                                           (88, 'Man trägt es an der Hand gegen Kälte', 'Handschuh'),
                                           (89, 'Etwas, das man sich um den Hals legt im Winter', 'Schal'),
                                           (90, 'Kleines Insekt, das Honig macht', 'Biene'),
                                           (91, 'Ein Gerät zum Spielen von Videospielen', 'Konsole'),
                                           (92, 'Farbige Flüssigkeit zum Malen', 'Farbe'),
                                           (93, 'Mit diesem Gerät sieht man weit entfernte Dinge näher', 'Fernrohr'),
                                           (94, 'Eine große Uhr mit Glockenschlag', 'Turmuhr'),
                                           (95, 'Kleiner Flugkörper aus Papier', 'Papierflieger'),
                                           (96, 'Gerät, das Musik abspielt', 'Radio'),
                                           (97, 'Tier mit langem Schwanz, das oft Käse frisst', 'Maus'),
                                           (98, 'Man isst es mit Löffel, manchmal süß oder salzig', 'Suppe'),
                                           (99, 'Kleines Boot, das man mit Muskelkraft bewegt', 'Ruderboot'),
                                           (100, 'Ein Ding, das man anzieht, wenn man schlafen geht', 'Schlafanzug');
